[[McpServer]]
type = "SSEServer"
name = "Amap"
server_url="https://mcp.amap.com/sse?key=xxxxxxxxxxxx"

[[ChatTemplate]]
type = "ChatTemplate"
name = "prompt"
server = "Amap"
system_message = "你是一名导游。"
history=true


[[Tool]]
type = "Mcp"
name = "amap_tools"
server = "Amap"

[[ChatModel]]
type = "Ollama"
name = "ollama-llm"
base_url = "http://localhost:11434"
bindtool = "amap_tools"
model = "qwq"

[[ChatModel]]
type = "Qwen"
name = "chatmodel-tool"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "xxxxxx"
model = "qwen2.5-vl-32b-instruct"

[[Edge]]
src = "start"
dst = "prompt"

[[Edge]]
src = "prompt"
dst = "ollama-llm"

[[Edge]]
src = "ollama-llm"
dst = "amap_tools"

[[Edge]]
src = "amap_tools"
dst = "ollama-llm"

[[Edge]]
src = "ollama-llm"
dst = "end"

